DROP TABLE IF EXISTS OFFERINGS;
CREATE TABLE OFFERINGS(
    `TABLE_ID` INT(32) AUTO_INCREMENT COMMENT '表ID' ,
    `CREATED_TIME` DATETIME   COMMENT '创建时间' ,
    `PAPER_TYPE` VARCHAR(90)   COMMENT '贡品种类' ,
    `UPDATED_TIME` DATETIME   COMMENT '更新时间' ,
    PRIMARY KEY (TABLE_ID)
)  COMMENT = '贡品';

DROP TABLE IF EXISTS LEAVE_COMMENTS;
CREATE TABLE LEAVE_COMMENTS(
    `TABLE_ID` INT(32) AUTO_INCREMENT COMMENT '表ID' ,
    `CREATED_TIME` DATETIME   COMMENT '创建时间' ,
    `WORDS` VARCHAR(900)   COMMENT '留言内容' ,
    `USER_ID` INT(32) COMMENT '留言用户ID' ,
    `IS_DELETE` VARCHAR(1) NOT NULL  COMMENT '删除标志' ,
    PRIMARY KEY (TABLE_ID)
)  COMMENT = '留言';

DROP TABLE IF EXISTS PAPER;
CREATE TABLE PAPER(
    `TABLE_ID` INT AUTO_INCREMENT COMMENT '表ID' ,
    `CREATED_TIME` DATETIME   COMMENT '创建时间' ,
    `PAPER_TYPE` VARCHAR(32)   COMMENT '纸品种类' ,
    `PAPER_NUM` INT   COMMENT '数量' ,
    PRIMARY KEY (TABLE_ID)
)  COMMENT = '纸品';

DROP TABLE IF EXISTS CONTROL;
CREATE TABLE CONTROL(
    `TABLE_ID` INT(32) NOT NULL  COMMENT '表主键' ,
    `VISITOR_COUNT` INT   COMMENT '用户数量' ,
    PRIMARY KEY (TABLE_ID)
)  COMMENT = '控制表';

DROP TABLE IF EXISTS VISITOR;
CREATE TABLE VISITOR(
    `TABLE_ID` INT(32) AUTO_INCREMENT COMMENT '表ID' ,
    `MAC` VARCHAR(100)   COMMENT 'MAC地址' ,
    `TIME` DATETIME   COMMENT '访问时间' ,
    `IP` VARCHAR(100)   COMMENT 'IP地址' ,
    `MORAL_COUNT` INT(32)   COMMENT '功德值' ,
    `CLIENT` VARCHAR(100)   COMMENT '客户端' ,
    `NAME` VARCHAR(100)   COMMENT '用户名' ,
    PRIMARY KEY (TABLE_ID)
)  COMMENT = '访客表';

